version: "3.9"

services:
    nginx:
        image: nginx:1.21-alpine
        ports:
            - "8080:80"
        volumes:
            - ./docker/nginx/conf.d:/etc/nginx/conf.d:ro
            - ./:/var/www/html:ro
        depends_on:
            - php-fpm

    php-fpm:
        build:
            context: ./docker/php-fpm
        volumes:
            - ./:/var/www/html:rw
        depends_on:
            - postgres

    postgres:
        image: postgres:13.5-alpine
        ports:
            - "5432:5432"
        environment:
            POSTGRES_DB: ${POSTGRES_DB}
            POSTGRES_USER: ${POSTGRES_USER}
            POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        volumes:
            - database:/var/lib/postgresql/data:rw

volumes:
    database:
